CREATE TABLE IF NOT EXISTS assignment_submissions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    assignment_id BIGINT UNSIGNED NOT NULL,
    student_user_id BIGINT UNSIGNED NOT NULL,
    submission_type ENUM('file', 'link', 'text') NOT NULL,
    text_answer TEXT NULL,
    link_url VARCHAR(500) NULL,
    submitted_at DATETIME NULL,
    status ENUM('draft', 'submitted', 'late', 'graded') NOT NULL DEFAULT 'draft',
    score DECIMAL(6,2) NULL,
    teacher_feedback TEXT NULL,
    graded_by BIGINT UNSIGNED NULL,
    graded_at DATETIME NULL,
    result_released_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_assignment_submissions_assignment_student (assignment_id, student_user_id),
    KEY idx_assignment_submissions_student_status (student_user_id, status),
    KEY idx_assignment_submissions_assignment_status (assignment_id, status),
    CONSTRAINT fk_assignment_submissions_assignment FOREIGN KEY (assignment_id) REFERENCES assignments (id) ON DELETE CASCADE,
    CONSTRAINT fk_assignment_submissions_student FOREIGN KEY (student_user_id) REFERENCES users (id),
    CONSTRAINT fk_assignment_submissions_grader FOREIGN KEY (graded_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
