CREATE TABLE IF NOT EXISTS assessment_attempts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    assessment_id BIGINT UNSIGNED NOT NULL,
    student_user_id BIGINT UNSIGNED NOT NULL,
    class_id BIGINT UNSIGNED NOT NULL,
    started_at DATETIME NULL,
    submitted_at DATETIME NULL,
    status ENUM('not_started', 'in_progress', 'submitted', 'graded') NOT NULL DEFAULT 'not_started',
    auto_score DECIMAL(6,2) NULL,
    manual_score DECIMAL(6,2) NULL,
    final_score DECIMAL(6,2) NULL,
    graded_by BIGINT UNSIGNED NULL,
    graded_at DATETIME NULL,
    result_released_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_assessment_attempts_assessment_status (assessment_id, status),
    KEY idx_assessment_attempts_student_status (student_user_id, status),
    CONSTRAINT fk_assessment_attempts_assessment FOREIGN KEY (assessment_id) REFERENCES assessments (id) ON DELETE CASCADE,
    CONSTRAINT fk_assessment_attempts_student FOREIGN KEY (student_user_id) REFERENCES users (id),
    CONSTRAINT fk_assessment_attempts_class FOREIGN KEY (class_id) REFERENCES classes (id),
    CONSTRAINT fk_assessment_attempts_grader FOREIGN KEY (graded_by) REFERENCES users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
